import SwiftCLI

CLI.setup(name: "BitBar", version: "1.0.beta", description: "CLI for BitBar")
CLI.register(command: ShowPluginCommand())
CLI.register(command: HidePluginCommand())
CLI.register(command: InvokePluginCommand())
CLI.register(command: RefreshPluginsCommand())
CLI.register(command: ListPluginsCommand())
CLI.register(command: GetStoreValueCommand())
CLI.register(command: SetStoreValueCommand())
CLI.register(command: RefreshPluginCommand())
CLI.register(command: PushStoreValueCommand())
CLI.register(command: GetValueValueCommand())
CLI.register(command: ClearListCommand())
CLI.register(command: LogPluginCommand())
CLI.register(command: InfoPluginCommand())
_ = CLI.go()
